[343336663]
name = "ABigLong"
mmr = 70

[104326212]
name = "橙猫猫"
mmr = 105

[347301286]
name = "dddd"
mmr = 110

[136203837]
name = "谢谢你泰罗！"
mmr = 70

[138895739]
name = "反思"
mmr = 50

[169761162]
name = "Milana"
mmr = 75

[1253831730]
name = "<:uq"
mmr = 95

[240778278]
name = "JH-lemon"
mmr = 105

[162342459]
name = "飞起来了"
mmr = 35

[106524218]
name = "Fury.`"
mmr = 45

[164269982]
name = "三气归来！"
mmr = 15

[136359194]
name = "陈靖仇"
mmr = 65

[136223879]
name = "氧气少女武天然"
mmr = 55

[285090798]
name = "9class"
mmr = 20

[232250354]
name = "Jagten"
mmr = 30

[227230775]
name = "顾我"
mmr = 0

[142076877]
name = "0.0"
mmr = 60

[1086487223]
name = "Dalia"
mmr = 105
main_id = 104326212

[134693265]
name = "天鱼"
mmr = 0

[180455444]
name = "婶"
mmr = 0

[423188523]
name = "文斗刀塔丶请深爱"
mmr = 70
main_id = 136203837

[116758157]
name = "benzema"
mmr = 85

[110460264]
name = "Byzantineguard"
mmr = 45

[230487379]
name = "Bye Mbappe"
mmr = 110
main_id = 347301286

[240419487]
name = "Mayday"
mmr = 30

[910734914]
name = "一"
mmr = 50
